import { createFileRoute, Link } from "@tanstack/react-router";
import { AlertTriangle, CalendarDays, ClipboardList, Plus, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { DemoLabel, MetricCard, NotConnected, PageHeader, SectionHeading } from "@/components/dr-assist/ui";
import { RecordsTable } from "@/components/dr-assist/records-table";
import { SeverityChart, TrendChart } from "@/components/dr-assist/charts";
import { screenings } from "@/lib/dr-assist/sample-data";

export const Route = createFileRoute("/")({ head:()=>({meta:[{title:"Dashboard — DR-Assist"},{name:"description",content:"DR-Assist prototype screening overview."},{property:"og:title",content:"DR-Assist Dashboard"},{property:"og:description",content:"Prototype diabetic retinopathy screening workflow overview."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}), component: Dashboard });
function Dashboard(){ return <><PageHeader eyebrow="Screening command center" title="Hello Sir/Maam " description="Monitor the sample screening workflow and cases requiring attention." action={<Button asChild size="lg"><Link to="/screening/new"><Plus/>Start New Screening</Link></Button>}/><NotConnected/><div className="my-6 flex items-center justify-between"><p className="text-xs text-muted-foreground">All metrics on this page are fictional interface samples.</p><DemoLabel/></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Total screenings" value="1,248" note="Sample program total" icon={Users} trend="up"/><MetricCard label="Screenings today" value="19" note="Sample daily activity" icon={CalendarDays}/><MetricCard label="Referable cases" value="27" note="Demo flag count" icon={AlertTriangle}/><MetricCard label="Manual review" value="12" note="Awaiting fictional review" icon={ClipboardList}/></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.85fr]"><Card className="clinical-card"><CardContent className="p-5"><SectionHeading title="Screening trend" description="Last 7 days · sample volume" aside={<DemoLabel/>}/><TrendChart/></CardContent></Card><Card className="clinical-card"><CardContent className="p-5"><SectionHeading title="DR severity distribution" description="Sample category mix"/><SeverityChart/></CardContent></Card></div><Card className="clinical-card mt-6"><CardContent className="p-0"><div className="p-5"><SectionHeading title="Recent screenings" description="Fictional records for interface demonstration" aside={<Button asChild variant="ghost" size="sm"><Link to="/patients">View all</Link></Button>}/></div><RecordsTable records={screenings.slice(0,4)}/></CardContent></Card></>; }
