import { createFileRoute } from "@tanstack/react-router";
import { Search } from "lucide-react";
import { useMemo, useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { DemoLabel, PageHeader } from "@/components/dr-assist/ui";
import { RecordsTable } from "@/components/dr-assist/records-table";
import { patients } from "@/lib/dr-assist/sample-data";
export const Route=createFileRoute("/patients")({head:()=>({meta:[{title:"Patients — DR-Assist"},{name:"description",content:"Search fictional patient screening records in the DR-Assist prototype."},{property:"og:title",content:"Patients — DR-Assist"},{property:"og:description",content:"Prototype patient screening records."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Patients});
function Patients(){const[q,setQ]=useState("");const[status,setStatus]=useState("all");const rows=useMemo(()=>patients.filter(p=>(p.patientId.toLowerCase().includes(q.toLowerCase())||p.id.toLowerCase().includes(q.toLowerCase()))&&(status==="all"||(status==="referable"?p.referable:p.reviewStatus==="Manual review"))),[q,status]);return <><PageHeader eyebrow="Records" title="Patients" description="Search and review fictional screening records used to demonstrate the Phase 1 interface." action={<DemoLabel/>}/><Card className="clinical-card"><CardContent className="p-0"><div className="flex flex-col gap-3 border-b border-border p-4 sm:flex-row"><label className="relative flex-1"><span className="sr-only">Search patient records</span><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search patient or screening ID" className="pl-9"/></label><select aria-label="Filter patients" value={status} onChange={e=>setStatus(e.target.value)} className="h-9 rounded-md border border-input bg-background px-3 text-sm"><option value="all">All records</option><option value="referable">Referable</option><option value="review">Manual review</option></select></div><RecordsTable records={rows}/></CardContent></Card></>}
