import type { LucideIcon } from "lucide-react";
import { ArrowDownRight, ArrowUpRight, CircleAlert } from "lucide-react";
import type { ReactNode } from "react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { cn } from "@/lib/utils";
import type { ReviewStatus, Severity } from "@/lib/dr-assist/types";

export function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description: string; action?: ReactNode }) { return <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div>{eyebrow && <p className="mb-2 text-[11px] font-bold uppercase text-primary">{eyebrow}</p>}<h1 className="text-2xl font-semibold text-foreground sm:text-3xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{description}</p></div>{action}</div>; }
export function DemoLabel() { return <Badge variant="outline" className="border-primary/25 bg-primary/8 text-[10px] text-primary">DEMO DATA</Badge>; }
export function MetricCard({ label, value, note, icon: Icon, trend }: { label: string; value: string; note: string; icon: LucideIcon; trend?: "up" | "down" }) { return <Card className="clinical-card"><CardContent className="p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-3 text-3xl font-semibold text-foreground">{value}</p></div><span className="grid size-9 place-items-center rounded-md bg-primary/10 text-primary"><Icon className="size-4"/></span></div><p className="mt-4 flex items-center gap-1 text-[11px] text-muted-foreground">{trend === "up" ? <ArrowUpRight className="size-3 text-success"/> : trend === "down" ? <ArrowDownRight className="size-3 text-success"/> : null}{note}</p></CardContent></Card>; }
export function SeverityBadge({ value }: { value: Severity }) { const c = value === "No DR" ? "bg-success/10 text-success border-success/20" : value === "Mild" ? "bg-info/10 text-info border-info/20" : value === "Pending" ? "bg-muted text-muted-foreground border-border" : "bg-warning/10 text-warning border-warning/20"; return <Badge variant="outline" className={c}>{value}</Badge>; }
export function ReviewBadge({ value }: { value: ReviewStatus }) { return <span className={cn("inline-flex items-center gap-1.5 text-xs", value === "Reviewed" ? "text-success" : value === "Manual review" ? "text-destructive" : "text-warning")}><span className="size-1.5 rounded-full bg-current"/>{value}</span>; }
export function NotConnected({ compact = false }: { compact?: boolean }) { return <div className={cn("flex items-start gap-3 rounded-md border border-destructive/20 bg-destructive/8", compact ? "p-3" : "p-4")}><CircleAlert className="mt-0.5 size-4 shrink-0 text-destructive"/><div><p className="text-xs font-bold text-destructive">AI ENGINE NOT CONNECTED</p>{!compact && <p className="mt-1 text-xs leading-5 text-muted-foreground">Values shown in this prototype are interface examples only. No image analysis or medical prediction has been performed.</p>}</div></div>; }
export function SectionHeading({ title, description, aside }: { title: string; description?: string; aside?: ReactNode }) { return <div className="mb-4 flex items-start justify-between gap-4"><div><h2 className="text-base font-semibold text-foreground">{title}</h2>{description && <p className="mt-1 text-xs text-muted-foreground">{description}</p>}</div>{aside}</div>; }
