/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SystemRouteImport } from './routes/system'
import { Route as AnalysisScreeningIdRouteImport } from './routes/analysis.$screeningId'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'
import { Route as ReportsScreeningIdRouteImport } from './routes/reports.$screeningId'
import { Route as ScreeningNewRouteImport } from './routes/screening.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisScreeningIdRoute = AnalysisScreeningIdRouteImport.update({
  id: '/analysis/$screeningId',
  path: '/analysis/$screeningId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsScreeningIdRoute = ReportsScreeningIdRouteImport.update({
  id: '/$screeningId',
  path: '/$screeningId',
  getParentRoute: () => ReportsRoute,
} as any)
const ScreeningNewRoute = ScreeningNewRouteImport.update({
  id: '/screening/new',
  path: '/screening/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/patients': typeof PatientsRoute
  '/reports': typeof ReportsRouteWithChildren
  '/system': typeof SystemRoute
  '/analysis/$screeningId': typeof AnalysisScreeningIdRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/reports/$screeningId': typeof ReportsScreeningIdRoute
  '/screening/new': typeof ScreeningNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/patients': typeof PatientsRoute
  '/reports': typeof ReportsRouteWithChildren
  '/system': typeof SystemRoute
  '/analysis/$screeningId': typeof AnalysisScreeningIdRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/reports/$screeningId': typeof ReportsScreeningIdRoute
  '/screening/new': typeof ScreeningNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/patients': typeof PatientsRoute
  '/reports': typeof ReportsRouteWithChildren
  '/system': typeof SystemRoute
  '/analysis/$screeningId': typeof AnalysisScreeningIdRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/reports/$screeningId': typeof ReportsScreeningIdRoute
  '/screening/new': typeof ScreeningNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/patients'
    | '/reports'
    | '/system'
    | '/analysis/$screeningId'
    | '/api/analyze'
    | '/reports/$screeningId'
    | '/screening/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/patients'
    | '/reports'
    | '/system'
    | '/analysis/$screeningId'
    | '/api/analyze'
    | '/reports/$screeningId'
    | '/screening/new'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/patients'
    | '/reports'
    | '/system'
    | '/analysis/$screeningId'
    | '/api/analyze'
    | '/reports/$screeningId'
    | '/screening/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  PatientsRoute: typeof PatientsRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  SystemRoute: typeof SystemRoute
  AnalysisScreeningIdRoute: typeof AnalysisScreeningIdRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ScreeningNewRoute: typeof ScreeningNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$screeningId': {
      id: '/analysis/$screeningId'
      path: '/analysis/$screeningId'
      fullPath: '/analysis/$screeningId'
      preLoaderRoute: typeof AnalysisScreeningIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$screeningId': {
      id: '/reports/$screeningId'
      path: '/$screeningId'
      fullPath: '/reports/$screeningId'
      preLoaderRoute: typeof ReportsScreeningIdRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/screening/new': {
      id: '/screening/new'
      path: '/screening/new'
      fullPath: '/screening/new'
      preLoaderRoute: typeof ScreeningNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReportsRouteChildren {
  ReportsScreeningIdRoute: typeof ReportsScreeningIdRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsScreeningIdRoute: ReportsScreeningIdRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  PatientsRoute: PatientsRoute,
  ReportsRoute: ReportsRouteWithChildren,
  SystemRoute: SystemRoute,
  AnalysisScreeningIdRoute: AnalysisScreeningIdRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ScreeningNewRoute: ScreeningNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
